name: Presubmit
on: 
  pull_request:
    branches:
      - master
jobs: 
  openapi-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v4
        with:
          path: head
      - name: Check out master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: trunk
      - name: Validate OpenAPI Specs
        run: |
          'echo "# OpenAPI Validation for ${{ inputs.head_specs }}" >> $GITHUB_STEP_SUMMARY'
          'echo "Passed" >> $GITHUB_STEP_SUMMARY'
        shell: bash
      - name: Extract OpenAPI Diffs and Changelogs
        run: |
          'echo "# OpenAPI ChangeLogs" >> $GITHUB_STEP_SUMMARY'
          'echo "foo bar" >> $GITHUB_STEP_SUMMARY'
        shell: bash
      - name: Detect OpenAPI breakages
        run: |
          'echo "# Breaking Changes" >> $GITHUB_STEP_SUMMARY'
          'echo "None" >> $GITHUB_STEP_SUMMARY'
        shell: bash
      - name: Run OpenAPI Diffs
        uses: oasdiff/oasdiff-action/diff@main
        with:
          base: 'trunk/specs/bm_petstore.yml'
          revision: 'head/specs/bm_petstore.yml'
          fail-on-diff: false
          format: yaml
      - name: Run OpenAPI Breaking Change Detection
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          base: 'trunk/specs/bm_petstore.yml'
          revision: 'head/specs/bm_petstore.yml'
