name: Presubmit
on: [workflow_dispatch, pull_request]
jobs: 
  openapi-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v2
        with:
          path: head
      - name: Check out master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: base
      - name: Run OpenAPI Diff (HEAD vs master)
        uses: mvegter/openapi-diff-action@v0.23.5
        with:
          head-spec: head/bm_petstore/bm_pets.yaml
          base-spec: base/bm_petstore/bm_pets.yaml