name: Presubmit
on: 
  pull_request:
    branches:
      - master

jobs: 
  openapi-check:
    runs-on: ubuntu-latest

    # services:
    #   swagger-editor:
    #     image: swaggerapi/swagger-editor
    #     ports:
    #       - 80:8080

    steps:
      - name: Check out head branch
        uses: actions/checkout@v4
        with:
          path: head
      - name: Check out master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: trunk

      # - name: Validate OpenAPI definition
      #   uses: char0n/swagger-editor-validate@v1
      #   with:
      #     swagger-editor-url: 'http://localhost/'
      #     definition-file: 'head/bm_petstore/bm_pets.yml'

      - name: Run OpenAPI Diff
        uses: oasdiff/oasdiff-action/diff@main
        with:
          base: 'trunk/bm_petstore/bm_pets.yml'
          revision: 'head/bm_petstore/bm_pets.yml'
          format: html
      
      - name: Run OpenAPI Breaking Change Detection
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          base: 'trunk/bm_petstore/bm_pets.yml'
          revision: 'head/bm_petstore/bm_pets.yml'
