name: Presubmit
on: 
  pull_request:
    branches:
      - master

jobs: 
  openapi-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v4
        with:
          path: head
      - name: Check out master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: trunk
      - name: Run OpenAPI Diff
        uses: oasdiff/oasdiff-action/diff@main
        with:
          base: 'head/bm_petstore/bm_pets.yml'
          revision: 'trunk/bm_petstore/bm_pets.yml'
      - name: Run OpenAPI Breaking Change
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          base: 'head/bm_petstore/bm_pets.yml'
          revision: 'trunk/bm_petstore/bm_pets.yml'
