# CUJs:
#   - new api.yml added (OK)
#      - no trunk .yml file exists ! (OK)
#      - check validity, (OK)
#      - do NO diffs, changelogs, breaking changes (OK)
#   - api.yml file changed (OK)
#      - check validity, diffs, changelogs, breaking changes (OK)
#   - api.yml file deleted (OK)
#      - no head .yml file exists ! (OK)
#      - dont run anything (OK)
#   - api.yml files moved (restructure)
#      - no trunk .yml file exists !
#      - no head .yml file exists !
#      - we need to check that the generated package contents (NPM, Maven) are the same.

name: Presubmit
on: 
  pull_request:
    branches:
      - master
jobs: 
  get-affected-apis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          json: true
          escape_json: false
          files: |
             specs/*.yml

      - name: Job Output Debug
        run: |
          echo "::debug::get-affected-apis affected: ${{ steps.changed-files.outputs.all_changed_files }}"
          echo "::debug::get-affected-apis added: ${{ steps.changed-files.outputs.added_files }}"
          echo "::debug::get-affected-apis deleted: ${{ steps.changed-files.outputs.deleted_files }}"
          echo "::debug::get-affected-apis modified: ${{ steps.changed-files.outputs.modified_files }}"

    outputs:
      affected: ${{ steps.changed-files.outputs.all_changed_files }}
      added: ${{ steps.changed-files.outputs.added_files }}
      deleted: ${{ steps.changed-files.outputs.deleted_files }}
      modified: ${{ steps.changed-files.outputs.modified_files }}

  openapi-check:
    if: ${{ needs.get-affected-apis.outputs.affected }}
    needs: [get-affected-apis]

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix: 
        # apifile: [ "specs/bm_bugstore.yml", "specs/bm_petstore.yml" ]
        apifile: ${{ fromJSON(needs.get-affected-apis.outputs.affected) }}

    steps:
      - name: Check out head branch
        uses: actions/checkout@v4

      - name: Check out master branch
        # Run only if the file was modified (M)
        if: ${{ contains(needs.get-affected-apis.outputs.modified, matrix.apifile) }}
        uses: actions/checkout@v4
        with:
          ref: master
          path: trunk

      # Skip for now to speed up.
      # - name: OpenAPI Validation
      #   # Skip validation if the file was deleted.
      #   if: ${{ ! contains(needs.get-affected-apis.outputs.deleted, matrix.apifile) }}
      #   uses: char0n/swagger-editor-validate@v1
      #   with:
      #     definition-file: "${{ matrix.apifile }}"

      - name: Changelog Generation
        # Run only if the file was modified (M)
        if: ${{ contains(needs.get-affected-apis.outputs.modified, matrix.apifile) }}
        id: openapi-changelog
        uses: oasdiff/oasdiff-action/changelog@main
        continue-on-error: true
        with:
          base: 'trunk/${{ matrix.apifile }}'
          revision: '${{ matrix.apifile }}'

      - name: Breaking Change Detection
        # Run only if the file was modified (M)
        if: ${{ contains(needs.get-affected-apis.outputs.modified, matrix.apifile) }}
        id: openapi-breaking
        uses: oasdiff/oasdiff-action/breaking@main
        continue-on-error: true
        with:
          base: 'trunk/${{ matrix.apifile }}'
          revision: '${{ matrix.apifile }}'

      - name: Report OpenAPI Changelog Findings
        # Run only if the file was modified (M)
        if: ${{ contains(needs.get-affected-apis.outputs.modified, matrix.apifile) }}
        # TODO: Improve the report visuals using Markdown
        run: |
          echo "::warning file=${{ matrix.apifile }}::OpenAPI changelog at: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          echo "${{ join(steps.openapi-changelog.outputs.*,'\n') }}" >> $GITHUB_STEP_SUMMARY