# CUJs:
#   - new api.yml added (OK)
#      - no trunk .yml file exists ! (OK)
#      - check validity, (OK)
#      - do NO diffs, changelogs, breaking changes (OK)
#   - api.yml file changed (OK)
#      - check validity, diffs, changelogs, breaking changes (OK)
#   - api.yml file deleted (OK)
#      - no head .yml file exists ! (OK)
#      - dont run anything (OK)
#   - api.yml files moved (restructure)
#      - no trunk .yml file exists !
#      - no head .yml file exists !
#      - we need to check that the generated package contents (NPM, Maven) are the same.

name: Presubmit
on: 
  pull_request:
    branches:
      - master
jobs: 
  get-affected-apis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
             specs/*.yml

    outputs:
      affected: ${{ steps.changed-files.all_changed_files }}
      added: ${{ steps.changed-files.added_files }}
      deleted: ${{ steps.changed-files.deleted_files }}
      modified: ${{ steps.changed-files.modified_files }}

  openapi-check:
    if: ${{ needs.get-affected-apis.outputs.affected }}
    needs: get-affected-apis

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        apifile: ${{ needs.get-affected-apis.outputs.affected }}

    steps:
      - name: Check out head branch
        uses: actions/checkout@v4
        with:
          path: head

      - name: Check out master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: trunk

      - name: OpenAPI Validation
        # Skip validation if the file was deleted.
        if: contains(${{ needs.get-affected-apis.outputs.deleted}}, ${{ matrix.apifile }}) == 'false'
        run: |
          echo "Validating trunk/${{ matrix.apifile }}"

      - name: OpeanAPI Diff
        # Run only if the file was modified (M)
        if: contains(${{ needs.get-affected-apis.outputs.modified}}, ${{ matrix.apifile }}) == 'true'
        run: |
          echo "Diffing trunk/${{ matrix.apifile }} vs head/${{ matrix.apifile }}"

      - name: Changelog Generation
        # Run only if the file was modified (M)
        if: contains(${{ needs.get-affected-apis.outputs.modified}}, ${{ matrix.apifile }}) == 'true'
        run: |
          echo "Changelog trunk/${{ matrix.apifile }} vs head/${{ matrix.apifile }}"

      - name: Breaking Change Detection
        # Run only if the file was modified (M)
        if: contains(${{ needs.get-affected-apis.outputs.modified}}, ${{ matrix.apifile }}) == 'true'
        run: |
          echo "Changelog trunk/${{ matrix.apifile }} vs head/${{ matrix.apifile }}"


      # - name: Validate OpenAPI definition (head)
      #   if: 
      #   uses: char0n/swagger-editor-validate@v1
      #   with:
      #     definition-file: "trunk/${{ matrix.apifile }}"

      # - name: Run OpenAPI Diffs
      #   if: steps.head_apifile_exists.outputs.files_exists == 'true' && steps.trunk_apifile_exists.outputs.files_exists == 'true'
      #   uses: oasdiff/oasdiff-action/diff@main
      #   with:
      #     base: 'trunk/specs/${{ matrix.apifile }}'
      #     revision: 'head/specs/${{ matrix.apifile }}'
      #     fail-on-diff: false
      #     format: yaml

      # - name: Run OpenAPI Breaking Change Detection
      #   if: steps.head_apifile_exists.outputs.files_exists == 'true' && steps.trunk_apifile_exists.outputs.files_exists == 'true'
      #   uses: oasdiff/oasdiff-action/breaking@main
      #   continue-on-error: true
      #   with:
      #     base: 'trunk/specs/${{ matrix.apifile }}'
      #     revision: 'head/specs/${{ matrix.apifile }}'

      # - name: Run OpenAPI Changelog Generation
      #   if: steps.head_apifile_exists.outputs.files_exists == 'true' && steps.trunk_apifile_exists.outputs.files_exists == 'true'
      #   uses: oasdiff/oasdiff-action/changelog@main
      #   with:
      #     base: 'trunk/specs/${{ matrix.apifile }}'
      #     revision: 'head/specs/${{ matrix.apifile }}'